[swarm_manager]
swarm_manager ansible_host=SWARM_MANAGER_IP ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem

[swarm_workers]
swarm_worker_a ansible_host=SWARM_WORKER_A_IP ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem
swarm_worker_b ansible_host=SWARM_WORKER_B_IP ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem

[swarm_nodes:children]
swarm_manager
swarm_workers
